#include <api/api.h>

protected const char* ocl_get_source_subtract_images(void)
{
	return
	"__kernel void subtract_images(__global unsigned char* img_a, __global unsigned char* img_b,\n"
	"                              __global unsigned char* result, int width, int height, int stride, int min_val, int max_val)\n"
	"{\n"
	"	int x = get_global_id(0);\n"
	"	int y = get_global_id(1);\n"
	"	if (x < width && y < height)\n"
	"	{\n"
	"		int idx = y * stride + x;\n"
	"		int diff = (int)img_a[idx] - (int)img_b[idx];\n"
	"		if (diff < min_val) diff = min_val;\n"
	"		if (diff > max_val) diff = max_val;\n"
	"		result[idx] = (unsigned char)diff;\n"
	"	}\n"
	"}\n";
}

protected const char* ocl_get_source_histogram(void)
{
	return
	"__kernel void histogram(__global unsigned char* image, __global unsigned int* hist,\n"
	"                        int width, int height, int stride)\n"
	"{\n"
	"	int x = get_global_id(0);\n"
	"	int y = get_global_id(1);\n"
	"	if (x < width && y < height)\n"
	"	{\n"
	"		int idx = y * stride + x;\n"
	"		unsigned char pixel = image[idx];\n"
	"		atomic_inc(&hist[pixel]);\n"
	"	}\n"
	"}\n";
}

protected const char* ocl_get_source_brightest_spot(void)
{
	return
	"float2 subpixel_refine(__global const unsigned char* img, int w, int h, int stride,\n"
	"                       int px, int py, int radius)\n"
	"{\n"
	"	float sx=0, sy=0, sw=0;\n"
	"	int xs=max(px-radius,0), ys=max(py-radius,0);\n"
	"	int xe=min(px+radius,w-1), ye=min(py+radius,h-1);\n"
	"	for(int y=ys; y<=ye; y++)\n"
	"		for(int x=xs; x<=xe; x++)\n"
	"		{\n"
	"			float wt=(float)img[y*stride+x];\n"
	"			sx+=wt*x; sy+=wt*y; sw+=wt;\n"
	"		}\n"
	"	return (sw>0) ? (float2)(sx/sw, sy/sw) : (float2)((float)px, (float)py);\n"
	"}\n"
	"\n"
	"__kernel void brightest_spot(__global const unsigned char* img,\n"
	"                             __global float* res, int w, int h, int stride,\n"
	"                             int cx, int cy, int rw, int rh, int sub_r)\n"
	"{\n"
	"	int hs=rw/2, hh=rh/2;\n"
	"	int xs=cx-hs, ys=cy-hh, xe=cx-hs+rw, ye=cy-hh+rh;\n"
	"	if(rw<=0||rh<=0) { xs=0; ys=0; xe=w; ye=h; }\n"
	"	xs=clamp(xs,0,w); ys=clamp(ys,0,h); xe=clamp(xe,0,w); ye=clamp(ye,0,h);\n"
	"	int bx=xs, by=ys;\n"
	"	unsigned char bv=0;\n"
	"	for(int y=ys; y<ye; y++)\n"
	"		for(int x=xs; x<xe; x++)\n"
	"			if(img[y*stride+x] > bv) { bv=img[y*stride+x]; bx=x; by=y; }\n"
	"	float2 sp = subpixel_refine(img, w, h, stride, bx, by, sub_r);\n"
	"	res[0]=sp.x; res[1]=sp.y; res[2]=(float)bv;\n"
	"}\n";
}

protected const char* ocl_get_source_matvec_bf16(void)
{
	return
	"__kernel void matvec_bf16(__global float *y,\n"
	"                          __global const float *x,\n"
	"                          __global const uint *W,\n"
	"                          int in_dim, int out_dim)\n"
	"{\n"
	"	int o = get_global_id(0);\n"
	"	if (o >= out_dim) return;\n"
	"	const uint *row = W + (size_t)o * in_dim;\n"
	"	float sum = 0.0f;\n"
	"	for (int k = 0; k < in_dim; ++k)\n"
	"	{\n"
	"		float w = as_float(row[k]);\n"
	"		sum = fma(w, x[k], sum);\n"
	"	}\n"
	"	y[o] = sum;\n"
	"}\n";
}

protected const char* ocl_get_source_matvec_bf16_fused(void)
{
	return
	"__kernel void matvec_bf16_fused(__global float *y0, __global float *y1,\n"
	"                                __global const float *x,\n"
	"                                __global const ushort *W0,\n"
	"                                __global const ushort *W1,\n"
	"                                int in_dim, int out_dim)\n"
	"{\n"
	"	int o = get_global_id(0);\n"
	"	if (o >= out_dim) return;\n"
	"	const ushort *row0 = W0 + (size_t)o * in_dim;\n"
	"	const ushort *row1 = W1 + (size_t)o * in_dim;\n"
	"	float sum0 = 0.0f, sum1 = 0.0f;\n"
	"	for (int k = 0; k < in_dim; ++k)\n"
	"	{\n"
	"		uint bits0 = (uint)row0[k] << 16;\n"
	"		uint bits1 = (uint)row1[k] << 16;\n"
	"		sum0 = fma(as_float(bits0), x[k], sum0);\n"
	"		sum1 = fma(as_float(bits1), x[k], sum1);\n"
	"	}\n"
	"	y0[o] = sum0;\n"
	"	y1[o] = sum1;\n"
	"}\n";
}

protected const char* ocl_get_source_matvec_f32(void)
{
	return
	"__kernel void matvec_f32(__global float *y,\n"
	"                          __global const float *x,\n"
	"                          __global const float *W,\n"
	"                          int in_dim, int out_dim)\n"
	"{\n"
	"	int o = get_global_id(0);\n"
	"	if (o >= out_dim) return;\n"
	"	const float *row = W + (size_t)o * in_dim;\n"
	"	float sum = 0.0f;\n"
	"	for (int k = 0; k < in_dim; ++k)\n"
	"		sum = fma(row[k], x[k], sum);\n"
	"	y[o] = sum;\n"
	"}\n";
}

protected const char* ocl_get_source_sd_attention_f32(void)
{
	return
	"__kernel void sd_attention_f32(\n"
	"	__global float *attn_out,\n"
	"	__global const float *q,\n"
	"	__global const float *k_cache,\n"
	"	__global const float *v_cache,\n"
	"	__global const float *new_k,\n"
	"	__global const float *new_v,\n"
	"	int new_frames,\n"
	"	int kv_len,\n"
	"	int n_heads,\n"
	"	int head_dim,\n"
	"	int qkv_dim,\n"
	"	int window,\n"
	"	float scale\n"
	")\n"
	"{\n"
	"	int sq = get_global_id(0);\n"
	"	int h  = get_global_id(1);\n"
	"\n"
	"	if (sq >= new_frames || h >= n_heads) return;\n"
	"\n"
	"	int abs_sq = kv_len + sq;\n"
	"	int sk_start = (abs_sq - window + 1 > 0) ? abs_sq - window + 1 : 0;\n"
	"	int sk_end = abs_sq;\n"
	"	int n_keys = sk_end - sk_start + 1;\n"
	"\n"
	"	const float *qh = q + sq * qkv_dim + h * head_dim;\n"
	"\n"
	"	float max_score = -1e30f;\n"
	"	float scores[72];\n"
	"\n"
	"	for (int j = 0; j < n_keys; j++)\n"
	"	{\n"
	"		int sk = sk_start + j;\n"
	"		const float *kh;\n"
	"		if (sk < kv_len)\n"
	"			kh = k_cache + sk * qkv_dim + h * head_dim;\n"
	"		else\n"
	"			kh = new_k + (sk - kv_len) * qkv_dim + h * head_dim;\n"
	"\n"
	"		float dot = 0.0f;\n"
	"		for (int d = 0; d < head_dim; d++)\n"
	"			dot += qh[d] * kh[d];\n"
	"		scores[j] = dot * scale;\n"
	"		if (scores[j] > max_score) max_score = scores[j];\n"
	"	}\n"
	"\n"
	"	float sum_exp = 0.0f;\n"
	"	for (int j = 0; j < n_keys; j++)\n"
	"	{\n"
	"		scores[j] = exp(scores[j] - max_score);\n"
	"		sum_exp += scores[j];\n"
	"	}\n"
	"	float inv_sum = 1.0f / sum_exp;\n"
	"\n"
	"	float *out = attn_out + sq * qkv_dim + h * head_dim;\n"
	"	for (int d = 0; d < head_dim; d++)\n"
	"		out[d] = 0.0f;\n"
	"\n"
	"	for (int j = 0; j < n_keys; j++)\n"
	"	{\n"
	"		int sk = sk_start + j;\n"
	"		const float *vh;\n"
	"		if (sk < kv_len)\n"
	"			vh = v_cache + sk * qkv_dim + h * head_dim;\n"
	"		else\n"
	"			vh = new_v + (sk - kv_len) * qkv_dim + h * head_dim;\n"
	"\n"
	"		float w = scores[j] * inv_sum;\n"
	"		for (int d = 0; d < head_dim; d++)\n"
	"			out[d] += vh[d] * w;\n"
	"	}\n"
	"}\n";
}

protected const char* ocl_get_source_sd_qkv_proj_f32(void)
{
	return
	"__kernel void sd_qkv_proj_f32(\n"
	"	__global float *q,\n"
	"	__global float *k,\n"
	"	__global float *v,\n"
	"	__global const float *x_norm,\n"
	"	__global const float *Wq,\n"
	"	__global const float *Wk,\n"
	"	__global const float *Wv,\n"
	"	int new_frames,\n"
	"	int dec_hidden,\n"
	"	int qkv_dim\n"
	")\n"
	"{\n"
	"	int o = get_global_id(0);\n"
	"	int s = get_global_id(1);\n"
	"\n"
	"	if (o >= qkv_dim || s >= new_frames) return;\n"
	"\n"
	"	const float *xs = x_norm + (size_t)s * dec_hidden;\n"
	"	const float *row_q = Wq + (size_t)o * dec_hidden;\n"
	"	const float *row_k = Wk + (size_t)o * dec_hidden;\n"
	"	const float *row_v = Wv + (size_t)o * dec_hidden;\n"
	"\n"
	"	float sum_q = 0.0f, sum_k = 0.0f, sum_v = 0.0f;\n"
	"	for (int i = 0; i < dec_hidden; ++i)\n"
	"	{\n"
	"		float xi = xs[i];\n"
	"		sum_q += row_q[i] * xi;\n"
	"		sum_k += row_k[i] * xi;\n"
	"		sum_v += row_v[i] * xi;\n"
	"	}\n"
	"\n"
	"	size_t idx = (size_t)s * qkv_dim + o;\n"
	"	q[idx] = sum_q;\n"
	"	k[idx] = sum_k;\n"
	"	v[idx] = sum_v;\n"
	"}\n";
}

protected const char* ocl_get_source_sd_output_proj_f32(void)
{
	return
	"__kernel void sd_output_proj_f32(\n"
	"	__global float *hidden,\n"
	"	__global const float *attn_out,\n"
	"	__global const float *Wo,\n"
	"	__global const float *layer_scale,\n"
	"	int new_frames,\n"
	"	int dec_hidden,\n"
	"	int qkv_dim\n"
	")\n"
	"{\n"
	"	int o = get_global_id(0);\n"
	"	int s = get_global_id(1);\n"
	"\n"
	"	if (o >= dec_hidden || s >= new_frames) return;\n"
	"\n"
	"	const float *attn = attn_out + (size_t)s * qkv_dim;\n"
	"	const float *row = Wo + (size_t)o * qkv_dim;\n"
	"\n"
	"	float sum = 0.0f;\n"
	"	for (int i = 0; i < qkv_dim; ++i)\n"
	"		sum += row[i] * attn[i];\n"
	"\n"
	"	if (layer_scale)\n"
	"		sum *= layer_scale[o];\n"
	"\n"
	"	hidden[(size_t)s * dec_hidden + o] += sum;\n"
	"}\n";
}

protected const char* ocl_get_source_sd_attention_out_f32(void)
{
	return
	"__kernel void sd_attention_out_f32(\n"
	"	__global float *hidden,\n"
	"	__global const float *q,\n"
	"	__global const float *k_cache,\n"
	"	__global const float *v_cache,\n"
	"	__global const float *new_k,\n"
	"	__global const float *new_v,\n"
	"	__global const float *Wo,\n"
	"	__global const float *layer_scale,\n"
	"	int new_frames,\n"
	"	int kv_len,\n"
	"	int n_heads,\n"
	"	int head_dim,\n"
	"	int qkv_dim,\n"
	"	int dec_hidden,\n"
	"	int window,\n"
	"	float scale\n"
	")\n"
	"{\n"
	"	int sq = get_global_id(0);\n"
	"	if (sq >= new_frames) return;\n"
	"\n"
	"	int abs_sq = kv_len + sq;\n"
	"	int sk_start = (abs_sq - window + 1 > 0) ? abs_sq - window + 1 : 0;\n"
	"	int sk_end = abs_sq;\n"
	"	int n_keys = sk_end - sk_start + 1;\n"
	"\n"
	"	for (int h = 0; h < n_heads; ++h)\n"
	"	{\n"
	"		const float *qh = q + (size_t)sq * qkv_dim + h * head_dim;\n"
	"\n"
	"		float max_score = -1e30f;\n"
	"		float scores[72];\n"
	"\n"
	"		for (int j = 0; j < n_keys; ++j)\n"
	"		{\n"
	"			int sk = sk_start + j;\n"
	"			const float *kh;\n"
	"			if (sk < kv_len)\n"
	"				kh = k_cache + (size_t)sk * qkv_dim + h * head_dim;\n"
	"			else\n"
	"				kh = new_k + (size_t)(sk - kv_len) * qkv_dim + h * head_dim;\n"
	"\n"
	"			float dot = 0.0f;\n"
	"			for (int d = 0; d < head_dim; ++d)\n"
	"				dot += qh[d] * kh[d];\n"
	"			scores[j] = dot * scale;\n"
	"			if (scores[j] > max_score) max_score = scores[j];\n"
	"		}\n"
	"\n"
	"		float sum_exp = 0.0f;\n"
	"		for (int j = 0; j < n_keys; ++j)\n"
	"		{\n"
	"			scores[j] = exp(scores[j] - max_score);\n"
	"			sum_exp += scores[j];\n"
	"		}\n"
	"		float inv_sum = 1.0f / sum_exp;\n"
	"\n"
	"		float attn_head[64];\n"
	"		for (int d = 0; d < head_dim; ++d)\n"
	"			attn_head[d] = 0.0f;\n"
	"\n"
	"		for (int j = 0; j < n_keys; ++j)\n"
	"		{\n"
	"			int sk = sk_start + j;\n"
	"			const float *vh;\n"
	"			if (sk < kv_len)\n"
	"				vh = v_cache + (size_t)sk * qkv_dim + h * head_dim;\n"
	"			else\n"
	"				vh = new_v + (size_t)(sk - kv_len) * qkv_dim + h * head_dim;\n"
	"\n"
	"			float w = scores[j] * inv_sum;\n"
	"			for (int d = 0; d < head_dim; ++d)\n"
	"				attn_head[d] += vh[d] * w;\n"
	"		}\n"
	"\n"
	"		for (int o = 0; o < dec_hidden; ++o)\n"
	"		{\n"
	"			const float *row = Wo + (size_t)o * qkv_dim + h * head_dim;\n"
	"			float sum = 0.0f;\n"
	"			for (int d = 0; d < head_dim; ++d)\n"
	"				sum += row[d] * attn_head[d];\n"
	"			if (layer_scale)\n"
	"				sum *= layer_scale[o];\n"
	"			hidden[(size_t)sq * dec_hidden + o] += sum;\n"
	"		}\n"
	"	}\n"
	"}\n";
}

protected const char* ocl_get_source_sd_norm_qkv_f32(void)
{
	return
	"__kernel void sd_norm_qkv_f32(\n"
	"	__global float *q,\n"
	"	__global float *k,\n"
	"	__global float *v,\n"
	"	__global const float *hidden,\n"
	"	__global const float *norm_weight,\n"
	"	__global const float *Wq,\n"
	"	__global const float *Wk,\n"
	"	__global const float *Wv,\n"
	"	int new_frames,\n"
	"	int dec_hidden,\n"
	"	int qkv_dim,\n"
	"	float eps\n"
	")\n"
	"{\n"
	"	int o = get_global_id(0);\n"
	"	int s = get_global_id(1);\n"
	"\n"
	"	if (o >= qkv_dim || s >= new_frames) return;\n"
	"\n"
	"	const float *xs = hidden + (size_t)s * dec_hidden;\n"
	"\n"
	"	/* RMSNorm */\n"
	"	float sum_sq = 0.0f;\n"
	"	for (int i = 0; i < dec_hidden; ++i)\n"
	"		sum_sq += xs[i] * xs[i];\n"
	"	float inv_rms = 1.0f / sqrt(sum_sq / (float)dec_hidden + eps);\n"
	"\n"
	"	const float *row_q = Wq + (size_t)o * dec_hidden;\n"
	"	const float *row_k = Wk + (size_t)o * dec_hidden;\n"
	"	const float *row_v = Wv + (size_t)o * dec_hidden;\n"
	"\n"
	"	float sum_q = 0.0f, sum_k = 0.0f, sum_v = 0.0f;\n"
	"	for (int i = 0; i < dec_hidden; ++i)\n"
	"	{\n"
	"		float xn = xs[i] * inv_rms * norm_weight[i];\n"
	"		sum_q += row_q[i] * xn;\n"
	"		sum_k += row_k[i] * xn;\n"
	"		sum_v += row_v[i] * xn;\n"
	"	}\n"
	"\n"
	"	size_t idx = (size_t)s * qkv_dim + o;\n"
	"	q[idx] = sum_q;\n"
	"	k[idx] = sum_k;\n"
	"	v[idx] = sum_v;\n"
	"}\n";
}

protected const char* ocl_get_source_iwt_flux(void)
{
    return
    "__kernel void iwt_flux(\n"
    "    __global const double* I,\n"
    "    __global const double* K,\n"
    "    __global double* sumJ,\n"
    "    int N,\n"
    "    int batch_start,\n"
    "    int batch_end)\n"
    "{\n"
    "    int i = get_global_id(0);\n"
    "    int idx = batch_start + i;\n"
    "    if (idx >= batch_end) return;\n"
    "\n"
    "    double sum = 0.0;\n"
    "    double Ii = I[idx];\n"
    "    for (int j = 0; j < N; j++)\n"
    "    {\n"
    "        double diff = Ii - I[j];\n"
    "        sum += K[idx * N + j] * diff;\n"
    "    }\n"
    "    sumJ[idx] = sum;\n"
    "}\n";
}

protected const char* ocl_get_source_iwt_q(void)
{
    return
    "__kernel void iwt_q(\n"
    "    __global const double* sumJ,\n"
    "    __global double* Q,\n"
    "    int N)\n"
    "{\n"
    "    int i = get_global_id(0);\n"
    "    if (i >= N) return;\n"
    "\n"
    "    // Q_i = sum_j J_ji - sum_j J_ij\n"
    "    // Mit J_ij = sumJ_i? Nein, J_ij ist der Fluss von i nach j.\n"
    "    // Wir brauchen J_ji = -J_ij, also Q_i = -2 * sumJ_i?\n"
    "    // ACHTUNG: Das ist nur korrekt, wenn K symmetrisch ist!\n"
    "    // Für den Test mit K symmetrisch: Q_i = -2 * sumJ_i\n"
    "    Q[i] = -2.0 * sumJ[i];\n"
    "}\n";
}

protected const char* ocl_get_source_iwt_update_info(void)
{
    return
    "__kernel void iwt_update_info(\n"
    "    __global double* I,\n"
    "    __global const double* sumJ,\n"
    "    double DT,\n"
    "    int N)\n"
    "{\n"
    "    int i = get_global_id(0);\n"
    "    if (i >= N) return;\n"
    "\n"
    "    I[i] = I[i] + sumJ[i] * DT;\n"
    "}\n";
}

protected const char* ocl_get_source_iwt_update_coupling(void)
{
    return
    "__kernel void iwt_update_coupling(\n"
    "    __global const double* I,\n"
    "    __global double* K,\n"
    "    __global const double* Q,\n"      // NEU
    "    double DT,\n"
    "    double ETA,\n"
    "    double LAMBDA,\n"
    "    double GAMMA,\n"                  // NEU
    "    int N,\n"
    "    int batch_start,\n"
    "    int batch_end)\n"
    "{\n"
    "    int i = get_global_id(0);\n"
    "    int idx = batch_start + i;\n"
    "    if (idx >= batch_end) return;\n"
    "\n"
    "    double Ii = I[idx];\n"
    "    double Qi = Q[idx];\n"
    "    for (int j = 0; j < N; j++)\n"
    "    {\n"
    "        double diff = Ii - I[j];\n"
    "        double Kij = K[idx * N + j];\n"
    "        double Qj = Q[j];\n"
    "        K[idx * N + j] = Kij + ETA * ((diff * diff) - 2.0 * LAMBDA * Kij) * DT - GAMMA * Qi * Qj * DT;\n"
    "    }\n"
    "}\n";
}
